version: '3.8'
services:
  app-node:
    image: fastapi:latest
    container_name: fastapi
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    build: 
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "80:80"